import { Oswald } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const oswald = Oswald({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
